export interface Producto {
  id: string;
  nombre: string;
  descripcion: string;
  precioOriginal: number;
  precioFinal: number;
  descuento: number;
  imagen: string;
  alt: string;
  rating: number;
  votos: number;
  categoria: 'snacks-salados' | 'galletas' | 'dulces' | 'ofertas';
  marca: string;
}

export const PRODUCTOS: Producto[] = [
  // ── SNACKS SALADOS ──
  {
    id: 'jalapeno',
    nombre: 'Papas INKA CHIPS Jalapeños Bolsa 142g',
    descripcion: 'Un clásico snack crocante, ideal para cualquier momento del día. Jalapeños con el toque perfecto de picor.',
    precioOriginal: 7.80,
    precioFinal: 7.00,
    descuento: 10,
    imagen: 'assets/img/inkachips.png',
    alt: 'Papas INKA CHIPS Jalapeños Bolsa 142g',
    rating: 4,
    votos: 12,
    categoria: 'snacks-salados',
    marca: 'inkachips'
  },
  {
    id: 'bbq',
    nombre: 'Papas INKA CHIPS BBQ & Cebolla Bolsa 135g',
    descripcion: 'Deliciosas papas crocantes con el inconfundible sabor BBQ y cebolla. El snack ideal para cualquier momento.',
    precioOriginal: 7.80,
    precioFinal: 7.00,
    descuento: 10,
    imagen: 'assets/img/bbq.png',
    alt: 'Papas INKA CHIPS BBQ & Cebolla Bolsa 135g',
    rating: 4,
    votos: 10,
    categoria: 'snacks-salados',
    marca: 'inkachips'
  },
  {
    id: 'cheetos',
    nombre: 'Cheetos Queso Picante X 180 Gr',
    descripcion: 'Crujientes y sabrosos Cheetos con ese toque picante que los hace irresistibles.',
    precioOriginal: 8.00,
    precioFinal: 7.00,
    descuento: 12,
    imagen: 'assets/img/cheetos-picante.png',
    alt: 'Cheetos Queso Picante X 180 Gr',
    rating: 4,
    votos: 18,
    categoria: 'snacks-salados',
    marca: 'cheetos'
  },
  {
    id: 'boliqueso',
    nombre: 'Boliqueso CHEETOS Bolsa 110g',
    descripcion: 'Bolitas crocantes de queso que se deshacen en la boca. Un clásico que no pasa de moda.',
    precioOriginal: 5.00,
    precioFinal: 4.50,
    descuento: 5,
    imagen: 'assets/img/cheetos-picante.png',
    alt: 'Boliqueso CHEETOS Bolsa 110g',
    rating: 4,
    votos: 7,
    categoria: 'snacks-salados',
    marca: 'cheetos'
  },
  {
    id: 'megaqueso',
    nombre: 'Piqueos Horneados CHEETOS Mega Queso Bolsa 200g',
    descripcion: 'Piqueos horneados con sabor intenso a queso. Perfectos para una gran merienda.',
    precioOriginal: 8.00,
    precioFinal: 6.00,
    descuento: 20,
    imagen: 'assets/img/cheetos-picante.png',
    alt: 'Piqueos Horneados CHEETOS Mega Queso Bolsa 200g',
    rating: 3,
    votos: 14,
    categoria: 'snacks-salados',
    marca: 'cheetos'
  },
  {
    id: 'flaminhot',
    nombre: 'Piqueos CHEETOS Flamin Hot Bolsa 120g',
    descripcion: 'Piqueos con el toque picante que solo los Flamin Hot pueden ofrecer. ¡Solo para valientes!',
    precioOriginal: 5.00,
    precioFinal: 4.00,
    descuento: 10,
    imagen: 'assets/img/cheetos-picante.png',
    alt: 'Piqueos CHEETOS Flamin Hot Bolsa 120g',
    rating: 4,
    votos: 6,
    categoria: 'snacks-salados',
    marca: 'cheetos'
  },
  {
    id: 'doritos',
    nombre: 'Tortillas de Maíz DORITOS Queso Atrevido Bolsa 190g',
    descripcion: 'Doritos intensos con sabor a queso atrevido, perfectos para cualquier ocasión.',
    precioOriginal: 9.00,
    precioFinal: 7.50,
    descuento: 15,
    imagen: 'assets/img/doritos-original.png',
    alt: 'Tortillas de Maíz DORITOS Queso Atrevido Bolsa 190g',
    rating: 5,
    votos: 22,
    categoria: 'snacks-salados',
    marca: 'doritos'
  },
  {
    id: 'lays',
    nombre: "Papas LAY'S Clásicas Bolsa 150g",
    descripcion: "Papas Lays originales, el sabor clásico que todos conocen y aman.",
    precioOriginal: 6.90,
    precioFinal: 6.00,
    descuento: 10,
    imagen: 'assets/img/inkachips.png',
    alt: "Papas LAY'S Clásicas Bolsa 150g",
    rating: 4,
    votos: 25,
    categoria: 'snacks-salados',
    marca: 'papas'
  },
  // ── GALLETAS ──
  {
    id: 'casinofresa',
    nombre: 'Galleta CASINO Sabor Fresa Bolsa 43g Paquete 6un',
    descripcion: 'Disfruta del inconfundible sabor a fresa en estas galletas Casino, ideales para compartir.',
    precioOriginal: 4.80,
    precioFinal: 4.00,
    descuento: 8,
    imagen: 'assets/img/casino-fresa.png',
    alt: 'Galleta CASINO Sabor Fresa',
    rating: 4,
    votos: 35,
    categoria: 'galletas',
    marca: 'casinos'
  },
  {
    id: 'casinomenta',
    nombre: 'Galleta CASINO Sixpack Sabor Menta Bolsa 43g Paquete 6un',
    descripcion: 'Refrescante sabor a menta en las clásicas galletas Casino.',
    precioOriginal: 4.80,
    precioFinal: 4.00,
    descuento: 8,
    imagen: 'assets/img/casino-menta.png',
    alt: 'Galleta CASINO Sabor Menta',
    rating: 4,
    votos: 35,
    categoria: 'galletas',
    marca: 'casinos'
  },
  {
    id: 'casinochocolate',
    nombre: 'Galleta CASINO Sabor Chocolate Bolsa 43g Paquete 6un',
    descripcion: 'Las clásicas galletas Casino con un delicioso sabor a chocolate.',
    precioOriginal: 4.80,
    precioFinal: 4.00,
    descuento: 8,
    imagen: 'assets/img/casino-chocolate.png',
    alt: 'Galleta CASINO Sabor Chocolate',
    rating: 4,
    votos: 35,
    categoria: 'galletas',
    marca: 'casinos'
  },
  {
    id: 'casinovainilla',
    nombre: 'Galleta CASINO Sabor Vainilla Bolsa 43g Paquete 6un',
    descripcion: 'Suave sabor a vainilla en las tradicionales galletas Casino.',
    precioOriginal: 4.80,
    precioFinal: 4.00,
    descuento: 8,
    imagen: 'assets/img/casino-vainilla.png',
    alt: 'Galleta CASINO Sabor Vainilla',
    rating: 4,
    votos: 35,
    categoria: 'galletas',
    marca: 'casinos'
  },
  {
    id: 'tentacion',
    nombre: 'Galleta VICTORIA Tentación Sabor de Naranja Bolsa 43g Paquete 6un',
    descripcion: 'La combinación perfecta entre suavidad y un toque cítrico de naranja.',
    precioOriginal: 5.00,
    precioFinal: 3.80,
    descuento: 12,
    imagen: 'assets/img/tentacion.png',
    alt: 'Galleta VICTORIA Tentación Sabor Naranja',
    rating: 5,
    votos: 42,
    categoria: 'galletas',
    marca: 'tentacion'
  },
  // ── DULCES ──
  {
    id: 'halls',
    nombre: 'Caramelos HALLS Menthol Lyptus Caja 12un',
    descripcion: 'Refresca tu día con los clásicos caramelos HALLS, alivio y frescura en cada pastilla.',
    precioOriginal: 22.80,
    precioFinal: 19.30,
    descuento: 15,
    imagen: 'assets/img/halls.png',
    alt: 'Caramelos HALLS Menthol Lyptus Caja 12un',
    rating: 4,
    votos: 33,
    categoria: 'dulces',
    marca: 'halls'
  },
  {
    id: 'chupetines',
    nombre: 'Chupetes GLOBO POP!! Relleno con chicle sabor fresa Bolsa 480Gr',
    descripcion: 'Los clásicos chupetines Globo Pop con relleno de chicle. Sabor fresa, diversión para grandes y chicos.',
    precioOriginal: 8.00,
    precioFinal: 7.00,
    descuento: 10,
    imagen: 'assets/img/chupetines.png',
    alt: 'Chupetes GLOBO POP!! sabor fresa',
    rating: 5,
    votos: 45,
    categoria: 'dulces',
    marca: 'chupetines'
  },
  {
    id: 'trident',
    nombre: 'Chicle TRIDENT Sin Azúcar sabor Sandia Envase 18un',
    descripcion: 'Chicles Trident sin azúcar con sabor a sandía, disfruta un aliento fresco y un toque frutal.',
    precioOriginal: 4.00,
    precioFinal: 2.80,
    descuento: 12,
    imagen: 'assets/img/trident.png',
    alt: 'Chicle TRIDENT Sin Azúcar sabor Sandia',
    rating: 4,
    votos: 27,
    categoria: 'dulces',
    marca: 'tridents'
  },
  {
    id: 'caramelos',
    nombre: 'Caramelos ARCOR Limón Bolsa 100Un',
    descripcion: 'Caramelos Arcor de limón, el toque cítrico ideal para cualquier momento del día.',
    precioOriginal: 10.40,
    precioFinal: 9.20,
    descuento: 8,
    imagen: 'assets/img/caramelo-limon.png',
    alt: 'Caramelos ARCOR Limón Bolsa 100Un',
    rating: 4,
    votos: 38,
    categoria: 'dulces',
    marca: 'caramelos'
  },
  // ── OFERTAS ──
  {
    id: 'pack-papas-lays-clasicas-bolsa-150g-x2un',
    nombre: "Pack Papas LAY'S Clásicas Bolsa 150g x2un",
    descripcion: "Pack de Papas LAY'S clásicas, sabor original para compartir.",
    precioOriginal: 13.00,
    precioFinal: 12.30,
    descuento: 5,
    imagen: 'assets/img/3pack-lays.png',
    alt: "Pack Papas LAY'S Clásicas x2",
    rating: 4,
    votos: 15,
    categoria: 'ofertas',
    marca: 'lays'
  },
  {
    id: 'pack-papas-lays-ondas-clasicas-bolsa-140g-x3un',
    nombre: "Pack Papas LAY'S Ondas Clásicas Bolsa 140g x3un",
    descripcion: "Disfruta el crujiente sabor de las Ondas LAY'S Clásicas en pack.",
    precioOriginal: 19.50,
    precioFinal: 17.40,
    descuento: 10,
    imagen: 'assets/img/3pack-ondas-clasicas.png',
    alt: "LAY'S Ondas Clásicas x3",
    rating: 4,
    votos: 21,
    categoria: 'ofertas',
    marca: 'lays'
  },
  {
    id: 'pack-papas-lays-ondas-picante-bolsa-140g-x3un',
    nombre: "Pack Papas LAY'S Ondas Picante Bolsa 140g x3un",
    descripcion: "Para los amantes del picante, papas LAY'S crujientes y sabrosas.",
    precioOriginal: 19.50,
    precioFinal: 17.40,
    descuento: 10,
    imagen: 'assets/img/3pack-ondas-picantes.png',
    alt: "LAY'S Ondas Picantes x3",
    rating: 5,
    votos: 40,
    categoria: 'ofertas',
    marca: 'lays'
  },
  {
    id: 'pack-papas-ondas-lays-con-mayonesa-bolsa-140g-x2un',
    nombre: "Pack Papas Ondas LAY'S con Mayonesa Bolsa 140g x2un",
    descripcion: "Papas LAY'S con sabor mayonesa, un toque cremoso único.",
    precioOriginal: 13.00,
    precioFinal: 12.30,
    descuento: 5,
    imagen: 'assets/img/2pack-ondas-mayonesa.png',
    alt: "LAY'S Mayonesa x2",
    rating: 3,
    votos: 10,
    categoria: 'ofertas',
    marca: 'lays'
  },
  {
    id: 'pack-tortillas-queso-doritos-dinamita-bolsa-80g-x3un',
    nombre: 'Pack Tortillas de Queso DORITOS Dinamita Bolsa 80g x3un',
    descripcion: 'Explosión de sabor intenso con los Doritos Dinamita.',
    precioOriginal: 19.50,
    precioFinal: 17.40,
    descuento: 10,
    imagen: 'assets/img/3pack-doritosDinamita.png',
    alt: 'Doritos Dinamita x3',
    rating: 3,
    votos: 8,
    categoria: 'ofertas',
    marca: 'doritos'
  },
  {
    id: 'pack-boliqueso-cheetos-bolsa-110g-x3un',
    nombre: 'Pack Boliqueso CHEETOS Bolsa 110g x3un',
    descripcion: 'Cheetos Boliqueso, el sabor a queso que nunca falla.',
    precioOriginal: 15.00,
    precioFinal: 13.50,
    descuento: 10,
    imagen: 'assets/img/3pack-cheetos-boliqueso.png',
    alt: 'Cheetos Boliqueso x3',
    rating: 4,
    votos: 23,
    categoria: 'ofertas',
    marca: 'cheetos'
  },
  {
    id: 'pack-piqueos-cheetos-mega-queso-bolsa-90g-x3un',
    nombre: 'Pack Piqueos CHEETOS Mega Queso Bolsa 90g x3un',
    descripcion: 'Mega sabor a queso en cada bocado de estos CHEETOS.',
    precioOriginal: 15.00,
    precioFinal: 13.50,
    descuento: 10,
    imagen: 'assets/img/3pack-cheetos-megaqueso.png',
    alt: 'Cheetos Mega Queso x3',
    rating: 4,
    votos: 30,
    categoria: 'ofertas',
    marca: 'cheetos'
  },
  {
    id: 'pack-piqueos-cheetos-flamin-hot-bolsa-120g-x3un',
    nombre: 'Pack Piqueos CHEETOS Flamin Hot Bolsa 120g x3un',
    descripcion: 'CHEETOS Flamin Hot, la intensidad picante que buscas.',
    precioOriginal: 15.00,
    precioFinal: 13.50,
    descuento: 10,
    imagen: 'assets/img/3pack-cheetos-flaminHot.png',
    alt: 'Cheetos Flamin Hot x3',
    rating: 4,
    votos: 19,
    categoria: 'ofertas',
    marca: 'cheetos'
  }
];