spring:
  application:
    name: snacktopia-backend
  datasource:
    url: postgresql://neondb_owner:npg_FZsBA8K6Noqe@ep-twilight-scene-aci85hpj-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${PORT:8080}
  error:
    include-message: always

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}

cors:
  allowed-origins:
    - ${FRONTEND_URL:http://localhost:4200}